### ISSUE TITLE
feature request: restructure code as an addon

### ISSUE THREAD

**Issue by elenakrittik** [Brutanian/SmartDialogue#1]
See [this](https://docs.godotengine.org/en/latest/community/asset_library/submitting_to_assetlib.html) article in Godot documentation and [this](https://github.com/godotengine/awesome-godot#plugins-and-scripts) list of already existing addons. You might also quickstart by opening Godot editor, clicking "Project" -> "Project Settings", then going to "Plugins" and pressing "Create".
This would make it a lot easier to install for users, especially if you add this on Godot Asset Library.

Thanks!

**Comment by Jay-Dorcat** [comment]
Hi thanks for your concern and idea, making something a plugin is not as easy as that I'm afraid, I would have to properly integrate it into the Godot engine interface.
I personally see it being more useful as an external tool. 
I understand why you would want this and trust me I'm trying to make this as easy to use as possible.
